新增工作

diff --git a/.github/workflows/build-i915-synology.yml b/.github/workflows/build-i915-synology.yml
--- a/.github/workflows/build-i915-synology.yml
+++ b/.github/workflows/build-i915-synology.yml
@@ -171,7 +171,7 @@ jobs:
             if [ -n "$SCONF_DIR" ] && [ -f "$SCONF_DIR/${{ inputs.syno_config }}" ]; then
               cp "$SCONF_DIR/${{ inputs.syno_config }}" "$KDIR/.config"
             else
-              echo "synoconfigs not found or ${ { inputs.syno_config } } missing." >&2
+              echo "synoconfigs not found or ${{ inputs.syno_config }} missing." >&2
               exit 1
             fi
           fi
